### ISSUE TITLE
add local translation support

### ISSUE THREAD

**Issue by camshaft** [poegroup/poe-ui-kit#5]
When developing applications locally it's nice to not require putting strings in an external system, especially when changing the content frequently.

I propose we have a `strings.yml` that looks something like this:

``` yaml
news-feed:
  description: A tab linking to list of events to which a user has subscribed
  en: News Feed
  images:
    - http://i.imgur.com/zBIYSXw.png
```

When developing locally we'd need a way to switch between the local strings and the ones from the api. When deployed, the app would upload the strings to the translation api and kick off the translation workflow.
